"use strict";

document.addEventListener("DOMContentLoaded", function() {
    const worksheetsGrid = document.getElementById("worksheetsGrid");
    const searchInput = document.getElementById("worksheetSearch");
    const filterButtons = document.querySelectorAll(".filter-btn");
    const noResults = document.getElementById("noResults");
    
    let worksheetsData = [];
    let currentCategory = "all";
    let searchQuery = "";

    // Fetch the live JSON generated by Python
    fetch("worksheets_data.json")
        .then(response => response.json())
        .then(data => {
            worksheetsData = data;
            renderWorksheets();
            handleAppDeepLinking();
        })
        .catch(error => console.error("Error loading JSON:", error));

    function renderWorksheets() {
        worksheetsGrid.innerHTML = "";
        
        const filteredList = worksheetsData.filter(item => {
            const matchesCategory = (currentCategory === "all" || item.categories.includes(currentCategory));
            const matchesSearch = item.title.toLowerCase().includes(searchQuery) || 
                                  item.subtitle.toLowerCase().includes(searchQuery);
            return matchesCategory && matchesSearch;
        });

        if (filteredList.length === 0) {
            noResults.classList.remove("hidden");
            worksheetsGrid.style.display = "none";
        } else {
            noResults.classList.add("hidden");
            worksheetsGrid.style.display = "grid"; // using CSS grid now
            
            filteredList.forEach(sheet => {
                const card = document.createElement("div");
                card.className = "worksheet-card";
                card.id = sheet.file_id; // Deep link anchor ID (e.g., "English_BigSmallAlphabetsNumbers")
                
                card.innerHTML = `
                    <div class="lang-badge">${sheet.badge}</div>
                    <div class="price-badge">${sheet.price}</div>
                    <div class="card-icon">📚</div>
                    <h2>${sheet.title}</h2>
                    <p class="card-subtitle">${sheet.subtitle}</p>
                    <a href="${sheet.buy_link}" class="buy-btn" target="_blank">Buy Now</a>
                `;
                worksheetsGrid.appendChild(card);
            });
        }
    }

    searchInput.addEventListener("input", function(e) {
        searchQuery = e.target.value.toLowerCase().trim();
        renderWorksheets();
    });

    filterButtons.forEach(btn => {
        btn.addEventListener("click", function() {
            filterButtons.forEach(b => b.classList.remove("active"));
            this.classList.add("active");
            currentCategory = this.dataset.category;
            renderWorksheets();
        });
    });

    // Deep Linking: Auto-scroll if opened from the React Native App
    function handleAppDeepLinking() {
        if (window.location.hash) {
            const targetId = window.location.hash.substring(1); // removes the '#'
            const targetCard = document.getElementById(targetId);
            
            if (targetCard) {
                // Scroll to card
                targetCard.scrollIntoView({ behavior: "smooth", block: "center" });
                // Apply CSS glow animation
                targetCard.classList.add("highlight-card");
                setTimeout(() => targetCard.classList.remove("highlight-card"), 2000);
            }
        }
    }
});